/* config.js */
const CONFIG = {
    LAMPADAS_VERTICAL: 7,    
    LAMPADAS_HORIZONTAL: 3,  
    ESPACO_LAMPADA: 36,      
    NUM_EIXOS_V: 10,          
    NUM_EIXOS_H: 4,         
    MARGEM: 60,

    VELOCIDADE_OPERADOR: 2.5,  
    RAIO_DETECCAO: 10,        // Mundo físico real
    TEMPO_REATIVO_MS: 8000,   
    DISTANCIA_PREDITIVA: 8    // Quantas lâmpadas à frente na sequência
};

CONFIG.CORREDOR_W = CONFIG.ESPACO_LAMPADA; 
CONFIG.CORREDOR_H = CONFIG.ESPACO_LAMPADA;
CONFIG.LARGURA_PRATELEIRA = CONFIG.ESPACO_LAMPADA * (CONFIG.LAMPADAS_HORIZONTAL + 1) - CONFIG.CORREDOR_W;
CONFIG.ALTURA_PRATELEIRA = CONFIG.ESPACO_LAMPADA * (CONFIG.LAMPADAS_VERTICAL + 1) - CONFIG.CORREDOR_H;
